-- Catalogue seed for D1 — generated from server/seed.js PRODUCTS (single source of truth).
-- Regenerate with: node scripts/generate-d1-seed.js > migrations/0002_seed.sql
-- Idempotent: clears existing rows first so it can be re-run safely.

DELETE FROM variants;
DELETE FROM products;

INSERT INTO products (id,slug,name,subtitle,family,tagline,story,description,top_notes,heart_notes,base_notes,ingredients,longevity,sillage,concentration,hero_image,gallery,accent,featured,sort_order) VALUES ('p_no01','no-01','No. 01','Eau de Parfum','Amber · Woody','The first accord we ever got right.','No. 01 began as a mistake — a saffron tincture left too long in aged oak. Six months later it had turned the colour of dark honey and smelled of a room someone had just left. We spent four years learning how to repeat the accident.','A fragrance built around warm amber, saffron and aged woods. It opens bright and resinous, settles into something darker within the hour, and stays close to the skin for most of a day.','Saffron, Pink Pepper, Bergamot','Amber, Orris Root, Dried Rose','Aged Oak, Labdanum, Vanilla Absolute','Kashmiri saffron threads · Calabrian bergamot · Florentine orris · Laotian oud oil · Madagascan vanilla absolute · Cistus labdanum','8–10 hours','Moderate — an arm''s length','22% parfum extrait','prod-1','["prod-1","prod-1-b","prod-1-d","prod-1-e"]','#C9A27E',1,1);
INSERT INTO variants (id,product_id,size_ml,price_paise,sku,stock) VALUES ('p_no01_50','p_no01',50,890000,'CM-N01-50',34);
INSERT INTO variants (id,product_id,size_ml,price_paise,sku,stock) VALUES ('p_no01_100','p_no01',100,1340000,'CM-N01-100',18);

INSERT INTO products (id,slug,name,subtitle,family,tagline,story,description,top_notes,heart_notes,base_notes,ingredients,longevity,sillage,concentration,hero_image,gallery,accent,featured,sort_order) VALUES ('p_solara','solara','Solara','Eau de Parfum','Citrus · Spice','Late afternoon, held still.','Built backwards from a memory of a courtyard in Seville at four in the afternoon — hot stone, cut citrus, someone grinding cardamom two floors up. The brief was to make the light itself smell like something.','The brightest thing we make. Bergamot and blood orange over green cardamom, landing on a warm amber base that keeps it from ever feeling thin.','Blood Orange, Bergamot, Petitgrain','Green Cardamom, Neroli, Ginger Lily','Amber, White Musk, Cedarwood','Sicilian blood orange · Guatemalan cardamom · Tunisian neroli · Virginian cedarwood · Amber accord · Ambrette seed','6–8 hours','Bright, then intimate','18% parfum extrait','prod-2','["prod-2","prod-2-b","ing-bergamot","ing-cardamom"]','#D08B4A',1,2);
INSERT INTO variants (id,product_id,size_ml,price_paise,sku,stock) VALUES ('p_solara_50','p_solara',50,840000,'CM-SOL-50',41);
INSERT INTO variants (id,product_id,size_ml,price_paise,sku,stock) VALUES ('p_solara_100','p_solara',100,1260000,'CM-SOL-100',22);

INSERT INTO products (id,slug,name,subtitle,family,tagline,story,description,top_notes,heart_notes,base_notes,ingredients,longevity,sillage,concentration,hero_image,gallery,accent,featured,sort_order) VALUES ('p_lune','lune','Lune','Eau de Parfum','Floral · Woody','For the hour after everyone has gone home.','Damascena rose picked before dawn, when the oil content peaks and the flower still smells green. We pair it with sandalwood distilled from trees older than the house, because rose on its own says too much.','Quiet, powdery, and warmer than it first appears. Rose and violet over creamy sandalwood and a soft musk that sits very close to the skin.','Damask Rose, Violet Leaf, Bergamot','Rose Absolute, Iris, Peony','Sandalwood, White Musk, Tonka Bean','Bulgarian rose absolute · Mysore-style sandalwood · Florentine iris butter · Tonka bean absolute · Ambrette musk','7–9 hours','Soft — close to the skin','20% parfum extrait','prod-3','["prod-3","prod-3-b","ing-rose","ing-sandalwood"]','#B08C86',1,3);
INSERT INTO variants (id,product_id,size_ml,price_paise,sku,stock) VALUES ('p_lune_50','p_lune',50,870000,'CM-LUN-50',27);
INSERT INTO variants (id,product_id,size_ml,price_paise,sku,stock) VALUES ('p_lune_100','p_lune',100,1310000,'CM-LUN-100',12);

INSERT INTO products (id,slug,name,subtitle,family,tagline,story,description,top_notes,heart_notes,base_notes,ingredients,longevity,sillage,concentration,hero_image,gallery,accent,featured,sort_order) VALUES ('p_noctis','noctis','Noctis','Extrait de Parfum','Oud · Leather','The darkest thing in the house.','Three years of failed trials. Oud is difficult — push it and the whole composition turns medicinal. We ended up building everything else first and adding the oud last, drop by drop, until it stopped smelling like oud and started smelling like weather.','Smoke, leather and resin. Incense over a spine of Laotian oud, finished with birch tar and a dry, mineral amber. Our most concentrated formulation.','Incense, Black Pepper, Elemi','Laotian Oud, Leather, Dried Plum','Birch Tar, Labdanum, Mineral Amber','Laotian oud oil · Somalian frankincense · Birch tar · Cistus labdanum · Atlas cedar · Castoreum accord','10–12 hours','Strong — it enters the room first','28% parfum extrait','prod-4','["prod-4","ing-oud","smoke","ing-sandalwood"]','#8E6A45',0,4);
INSERT INTO variants (id,product_id,size_ml,price_paise,sku,stock) VALUES ('p_noctis_50','p_noctis',50,960000,'CM-NOC-50',15);
INSERT INTO variants (id,product_id,size_ml,price_paise,sku,stock) VALUES ('p_noctis_100','p_noctis',100,1440000,'CM-NOC-100',7);

INSERT INTO products (id,slug,name,subtitle,family,tagline,story,description,top_notes,heart_notes,base_notes,ingredients,longevity,sillage,concentration,hero_image,gallery,accent,featured,sort_order) VALUES ('p_aurea','aurea','Aurea','Eau de Parfum','Honey · Tobacco','Sweet, but not kind.','Honey is the hardest note to use well — a gram too much and the whole thing collapses into dessert. Aurea holds it in tension against cured tobacco leaf and a bitter saffron top, so the sweetness never quite arrives.','Saffron and honey over cured tobacco and tonka. Rich and slightly animalic, with a dry finish that keeps it from ever reading as gourmand.','Saffron, Honey Absolute, Osmanthus','Tobacco Leaf, Immortelle, Hay','Tonka Bean, Benzoin, Sandalwood','Kashmiri saffron · Provençal honey absolute · Cured Virginia tobacco · Corsican immortelle · Siam benzoin','9–11 hours','Warm and carrying','21% parfum extrait','prod-5','["prod-5","ing-saffron","testimonial","texture-band"]','#C2913F',0,5);
INSERT INTO variants (id,product_id,size_ml,price_paise,sku,stock) VALUES ('p_aurea_50','p_aurea',50,790000,'CM-AUR-50',38);
INSERT INTO variants (id,product_id,size_ml,price_paise,sku,stock) VALUES ('p_aurea_100','p_aurea',100,1190000,'CM-AUR-100',20);

INSERT INTO products (id,slug,name,subtitle,family,tagline,story,description,top_notes,heart_notes,base_notes,ingredients,longevity,sillage,concentration,hero_image,gallery,accent,featured,sort_order) VALUES ('p_vesper','vesper','Vesper','Eau de Parfum','Smoke · Mineral','Cold air, and something burning far away.','The only fragrance we make that isn''t warm. Vetiver distilled from Haitian roots, vetted against a mineral accord built to smell like wet slate. It took eleven attempts to stop it smelling like a cellar.','Grey, dry and architectural. Smoked vetiver and ambergris over a cool mineral base, with just enough incense to keep it from going flat.','Juniper, Grapefruit Peel, Pink Pepper','Smoked Vetiver, Incense, Wet Slate','Ambergris, Cashmere Wood, Grey Musk','Haitian vetiver · Ambergris accord · Somalian frankincense · Mineral accord · Cashmeran · Juniper berry','8–10 hours','Cool and precise','19% parfum extrait','prod-6','["prod-6","smoke","cta","ing-oud"]','#8A8F8C',0,6);
INSERT INTO variants (id,product_id,size_ml,price_paise,sku,stock) VALUES ('p_vesper_50','p_vesper',50,920000,'CM-VES-50',24);
INSERT INTO variants (id,product_id,size_ml,price_paise,sku,stock) VALUES ('p_vesper_100','p_vesper',100,1380000,'CM-VES-100',11);

